//
//
export const AUTH_RESET = 'AUTH_RESET'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL'

export const AUTH_LOGIN_SUCCESS ='AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'

export const AUTH_UPDATE_SUCCESS ='AUTH_UPDATE_SUCCESS'
export const AUTH_UPDATE_FAIL = 'AUTH_UPDATE_FAIL'
