//
//
export const PROJECT_RESET = 'PROJECT_RESET'
export const PROJECT_REQUEST = 'PROJECT_REQUEST'

export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS'
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL'

export const PROJECT_REMOVE_SUCCESS = 'PROJECT_REMOVE_SUCCESS'
export const PROJECT_REMOVE_FAIL = 'PROJECT_REMOVE_FAIL'


export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS'
export const PROJECT_UPDATE_FAIL = 'PROJECT_UPDATE_FAIL'
